//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub use super::user::ActiveModel as UserActiveModel;
pub use super::user::Column as UserColumn;
pub use super::user::Entity as UserEntity;
pub use super::user::Model as UserModel;
